### ISSUE TITLE
Unable to create a SSH connection...

### ISSUE THREAD

**Issue by thornrose** [lstratman/EasyConnect#69]
On Windows 10, attempting to create a SSH connection, I get this error:
"Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Granados.strings.resources" was correctly embedded or linked into assembly "TerminalControl" at compile time, or that all the satellite assemblies required are loadable and fully signed."

Regional settings is "South Africa" but default Language is US English.

**Comment by lstratman** [comment]
This should be fixed so that all error messages for the SSH connection process can be displayed correctly.  I have also added a prompt for the username and password if you are starting an SSH connection through the URL bar instead of the bookmarks/favorites.

You can download a nightly build with this in it from [here](https://ci.appveyor.com/api/projects/lstratman/EasyConnect/artifacts/Installer/bin/Release/EasyConnect.msi) or you can wait a few days until I put out an official release.

**Comment by thornrose** [comment]
Thanks. Is there a way to increase the SSH connection timeout?

Eugene van Zyl

Cell phone: +27 (0)83 305 1173
Email: eugenevz@gmail.com

**Comment by xdontkillmeisuck** [comment]
When is the new build going to updated in the store?
