### ISSUE TITLE
RFB 3.8 not supported by server.

### ISSUE THREAD

**Issue by yecril71pl** [lstratman/EasyConnect#82]
I get this error when I connect to Ubuntu desktop.

**Comment by LazySmerf** [comment]
I am also getting this same message connecting to Lubuntu. I am running Vino Server.

**Comment by yecril71pl** [comment]
See also [Bug #1778581](https://bugs.launchpad.net/ubuntu/%2Bsource/vino/%2Bbug/1778581).

**Comment by lstratman** [comment]
Sorry for the delay, I've just gotten back into developing for this project.  This issue is do to limitations in the library that is used for VNC connections.  While the upcoming 3.0 release in a few days is going to focus on updating the UI and fixing some other issues, for the 3.1 release, I plan on re-writing the VNC support to be build on libvncserver, which gives us access to a wider set of RFB encoding, TLS support, etc.  That should fix this issue.

**Comment by lstratman** [comment]
Finally got time to finish the VNC rewrite, which is up on the download site, the Microsoft Store, and on winget.  The VNC plugin now uses a new VNC library ([MarcusW.VncClient](https://github.com/MarcusWichelmann/MarcusW.VncClient)), which fixes the RFB version support issue you were seeing.  It's been tested against Ubuntu, Windows, and MacOS VNC servers.
